version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_PASSWORD: root

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8035:80"
    environment:
      PMA_HOST: mysql
      PMA_PMADB: phpmyadmin
      MYSQL_ROOT_PASSWORD: root

  api:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./firebase-credentials.json:/app/firebase-credentials.json
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/api

  frontend:
    depends_on:
      - api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3003:8082"
    environment:
      API_URL: http://localhost:8000/api

volumes:
  db_data:
